### ISSUE TITLE
Better Example for FS Download URL

### ISSUE THREAD

**Issue by TarMint** [monday-consulting/firstspirit-docker#40]
Hi,

Can you give a clearer example how the Url to the FirstSpirit download server has to look? 
https://file.crownpeak.com/ isn't working for us.

Best regards

**Comment by TarMint** [comment]
Nevermind, we found out what part we were missing :-)

**Comment by theexiile1305** [comment]
@TarMint What was the missing part? Or @mschel, @omoroca , @fabiobaser, @malde Can you give me a brief hint to that url?

Many thanks in advance.

**Comment by malde** [comment]
Please don't randomly mention unrelated users.

**Comment by theexiile1305** [comment]
@malde Sorry. I thought from Github's suggestion that they might be responsible.
